# Generated by Django 5.1.4 on 2026-09-05 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Administrator'), ('MANAGER', 'Manager'), ('MEMBER', 'Member')], default='MEMBER', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='businesses.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['business__name', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('property_type', models.CharField(choices=[('LAND', 'Land'), ('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('AGRICULTURAL', 'Agricultural'), ('MIXED_USE', 'Mixed use'), ('OTHER', 'Other')], default='LAND', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('area_unit', models.CharField(default='sq ft', max_length=30)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('current_estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('ownership_status', models.CharField(choices=[('OWNED', 'Owned'), ('CO_OWNED', 'Co-owned'), ('LEASED', 'Leased'), ('UNDER_CONTRACT', 'Under contract'), ('PROSPECTIVE', 'Prospective')], default='OWNED', max_length=20)),
                ('intended_purpose', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('development_status', models.CharField(choices=[('RAW', 'Raw / undeveloped'), ('PLANNED', 'Planned'), ('IN_PROGRESS', 'In progress'), ('DEVELOPED', 'Developed'), ('ON_HOLD', 'On hold')], default='RAW', max_length=20)),
                ('image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='businesses.business')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='businessuser',
            constraint=models.UniqueConstraint(fields=('business', 'user'), name='unique_business_user'),
        ),
    ]
